config/routes.rb
Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'

  namespace :admin do
    resources :identities
    resources :videos
    resources :lyrics
    resources :track_providers
    resources :playlists
    resources :video_providers
    resources :tracks
    resources :users

    root to: "identities#index"
  end

  match '/auth/demo', to: 'sessions#demo', via: :get, as: :demo
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/auth/failure', to: 'errors#login_failed', via: [:get, :post]
  match '/logout', to: 'sessions#destroy', via: [:get, :post], as: :logout

  # You can have the root of your site routed with "root"
  root 'landing#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  resources :playlists, only: :index do
    resources :tracks, only: :show
  end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  enum access: %i[private public], _suffix: true

  belongs_to :identity, inverse_of: :playlists
  belongs_to :provider, class_name: 'TrackProvider', foreign_key: :track_provider_id, inverse_of: :playlists
  has_and_belongs_to_many :tracks, -> { includes(:video) }

  validates :ref,
            :title,
            :original_url,
            presence: true
  validates :ref, uniqueness: { scope: :track_provider_id }

  def self.find_or_create_from_api_result_and_identity!(result, identity)
      playlist = Playlist.create_with(result.merge(identity: identity)).find_or_create_by!(
        provider: identity.provider,
        ref: result[:ref]
      )
  end

  def fetch_tracks!
    raw_tracks = provider_class.new(identity.access_token).playlist_tracks(identity.uid, ref).reverse
    track_ids_with_existing_videos = Track.where(provider: identity.provider, ref: raw_tracks.map { |t| t[:ref] }).where.not(video_id: nil).pluck(:id)

    raw_tracks.map do |raw_track|
      track = Track.find_or_create_from_api_result_and_identity!(raw_track, identity)

      self.tracks << track unless tracks.include?(track)
      TrackVideosFetchingJob.perform_later(track) unless track_ids_with_existing_videos.include?(track.id)
    end
    self.save!
  end

  def self.select_first_playlist(playlists)
    unless first_playlist = playlists.detect { |p| p.default && p.tracks.size > 0 }
      first_playlist = playlists.detect { |p| p.tracks.size > 0 }
    end

    first_playlist
  end

  private

  def provider_class
    @provider_class ||= provider.name.camelize.constantize
  end
end

app/controllers/admin/playlists_controller.rb
module Admin
  class PlaylistsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :login_required

  def index
    respond_to do |format|
      format.html
      # format.xml  { render xml: @users }
      format.json do
        jsonPayload = { playlists: serialize_playlists(current_user.playlists_for_provider('deezer')) + serialize_playlists(current_user.playlists_for_provider('spotify')) }
        render json: jsonPayload
      end
    end
  end

  private

  def serialize_playlists(playlists)
    playlists.as_json(
      only: [:title, :ref, :picture_url, :duration],
      include: [
        provider: {
          only: :name
        },
        tracks: {
          only: [:title, :artist_name, :duration, :ref, :artist_image_url, :album_image_url],
          include: {
            video: {
              only: :ref,
              include: {
                provider: {
                  only: :name
                }
              }
            }
          }
        }
      ]
    )
  end
end

app/views/playlists/_loader.html.erb
<div class="loader-wrapper">
  <div class="loader">
    <div class="loader-bg">
      <div class="text icon-play2"></div>
    </div>
    <div class="mask"></div>
    <div class="spiner-holder-one animate-0-25-a">
      <div class="spiner-holder-two animate-0-25-b">
        <div class="loader-spiner" style=""></div>
      </div>
    </div>
    <div class="spiner-holder-one animate-25-50-a">
      <div class="spiner-holder-two animate-25-50-b">
        <div class="loader-spiner"></div>
      </div>
    </div>
    <div class="spiner-holder-one animate-50-75-a">
      <div class="spiner-holder-two animate-50-75-b">
        <div class="loader-spiner"></div>
      </div>
    </div>
    <div class="spiner-holder-one animate-75-100-a">
      <div class="spiner-holder-two animate-75-100-b">
        <div class="loader-spiner"></div>
      </div>
    </div>
  </div>
</div>

app/views/playlists/_playlist.html.erb
<li v-for="(playlist, index) of playlists"
  :class="[index == 0 ? 'selected' : '', 'playlist']"
  :data-title="playlist.title"
  :data-id="playlist.ref"
  :data-img="playlist.picture_url"
  :data-duration="playlist.duration"
  :data-tracks-count="playlist.tracks.size"
  :data-provider="playlist.provider.name"
  >
  {{ playlist.title }}
  <div class="menu-slide-wrapper tracks" style="display:none">
    <div class='menu-wrapper tracks'>
      <ul>
        <%= render partial: 'tracks' %>
      </ul>
    </div>
  </div>
</li>

app/views/playlists/_tracks.html.erb
<li v-for="(track, index) of playlist.tracks"
  :class="[index == 0 ? 'selected' : '', 'track']"
  :data-title="track.title"
  :data-artist="track.artist_name"
  :data-track-id="track.ref"
  :data-artist-picture="track.artist_image_url"
  :data-album-picture="track.album_image_url"
  :data-video-id="track.video.ref"
  :data-video-provider="track.video.provider.name"
  :data-playlist-id="playlist.ref"
  >
  <div class="track-title">{{ track.title }}</div>
  <div class="track-artist">{{ track.artist_name }}</div>
</li>

app/views/playlists/index.html.erb
<% content_for :javascript do %>
  <% javascript_include_tag '//cdn.jsdelivr.net/qtip2/2.2.0/jquery.qtip.min.js' %>
  <% javascript_pack_tag 'playlists' %>
<% end %>
<% content_for :stylesheet, stylesheet_link_tag('//cdn.jsdelivr.net/qtip2/2.2.0/jquery.qtip.css') %>

<div id="playlists-page" class="playlists-page">
  <div id="templates">
    <%= render 'loader' %>
    <div class="karaoke-menu">
     <div class="karaoke-bar"></div>
     <div class="karaoke-body">
       <div class="karaoke-track"></div>
       <div class="karaoke-box">
         Lyrics mode
         <div class="on-off">
           <button class="on-off-menu on">Yes</button>
           <button class="on-off-menu">No</button>
         </div>
       </div>
       <div class="karaoke-box">
         Lyrics offset
         <div class="on-off">
           <button class="on-off-menu on selected">&#9660;</button>
           <button class="on-off-menu off ">&#9650;</button>
         </div>
       </div>
     </div>
   </div>
  </div>

  <div id="menu">
    <div class="menu-top">
      <img src="<%= current_user.picture_url %>" alt="<%= current_user.login %>">
      <div class="user-name">
        <%= current_user.login %>
        <div class="menu-logout"><%= link_to 'Logout', logout_path %></div>
      </div>
      <div class="menu-expand"></div>
    </div>
    <div class="menu-cover">
      <div class="menu-cover-wrapper">
        <div class="menu-current">
          <div class="cover">
            <img :src="coverImageUrl" alt="">
          </div>
          <div class="cover-overlay">
            <img :src="coverOverlayUrl" alt="">
            <div class="infos">
              <div class="title">{{ currentPlaylistTitle }}</div>
              <div class="extras">
                <div class="nb_track"><span class="tracks-count">{{ currentPlaylistTracksCount }}</span> titles</div>
                <div class="nb_track duration">{{ currentPlaylistDuration }}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="menu-tools">
      <div class="menu-tools-wrapper">
        <div class="main-sub">
          <div class="left-side"></div>
          <div id="go-to-forward"><i class="icon-arrow-right"></i></div>
        </div>
        <div class="play-all">
          <div id='go-to-previous'><i class="icon-arrow-left"></i></div>
          <div class="play-tools">
            <i class="icon2-flag report" tooltip="Wrong video for this song"></i>
            <span class="karaoke-mode">
              <div class="karaoke-wrapper">
                <i class="icon-microphone"></i>
              </div>
            </span>
            <i class="icon-shuffle2"></i>
            <i class="icon-cw"></i>
            <i class="icon-cog"></i>
          </div>
        </div>
      </div>
    </div>
  <!--   <div class='search-playlist'>
      <input type="text" placeholder="Search for a playlist"><i class="fa fa-search"></i>
    </div>
   -->
    <div class="menu-slide playlists">
      <div class="menu-slide-wrapper">
  <!--       <div class="search"><input type="text" placeholder="Search in your playlists">
          <i class="icon-search2"></i>
        </div>
   -->
        <div id="playlists" class='menu-wrapper playlists'>
          <ul>
            <playlist-sidebar-item
              v-for="(playlist, index) of playlists"
              v-bind:selected="index == 0"
              v-bind:key="playlist.id"
              v-bind:playlist="playlist"
            ></playlist-sidebar-item>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div id="main-view">
    <div class="menu-icon"></div>
    <player v-bind:playlist="currentPlaylist" v-bind:player-options="{ autoplay: false }"></player>
    <div class="progress-bar">
      <div class="progress"></div>
    </div>
  </div>
</div>